Let's start with importing the required packages

In [2]:
#Loading the library with iris dataset
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
np.random.seed(0)

Creating an object called iris with iris data

In [3]:
iris = load_iris()
 
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()    #looking at what we have 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
#Adding a new column for the species name
df['Species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [7]:
#Creating teat and train data
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  is_train  
0  setosa      True  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [8]:
# creating dataframe with training and test rows
train, test = df[df['is_train'] == True], df[df['is_train'] == False]

In [9]:
#show the num of observations for the training and test dataframe
print('Number of observations in training data:', len(train))
print('Number of observations in test data:', len(test))

Number of observations in training data: 112
Number of observations in test data: 38


In [10]:
#Creates a list of the features column's name
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [11]:
#Converting each species name into digits
y = pd.factorize(train['Species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2], dtype=int64)

Creating a Random Forest Classifier

In [12]:
clf = RandomForestClassifier(n_jobs = 2, random_state = 0)

In [13]:
#Training the classifier
clf.fit(train[features], y)

C:\Users\anurag.s\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

Applying the trained Classifier to the Test

In [14]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [16]:
#Viewing the predicted probability of first 10 observations
clf.predict_proba(test[features][0:10])

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.9, 0.1, 0. ],
       [0.9, 0.1, 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ]])

Let us map names of the plants for each of the predicted plant class

In [17]:
preds = iris.target_names[clf.predict(test[features])]

#view the predicted species for first five observations

preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [18]:
#View the Actual Species for the first five Observations

test['Species'].head()

1     setosa
5     setosa
6     setosa
13    setosa
14    setosa
Name: Species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

Creating Confussion Matrix

In [19]:
pd.crosstab(test['Species'], preds, rownames = ['Actual Species'], colnames = ['Predicted species'])

Predicted species  setosa  versicolor  virginica
Actual Species                                  
setosa                 10           0          0
versicolor              0           9          0
virginica               0           1         18

Number of Accurate Prediction = 30
Number of Inaccurate Prediction = 2

## Model Accoracy = 30/32 * 100 = 93%

Thats Great, we predicted a the species of flower using Random Forest Classifier that gives us an accuracy of 93%